#! /bin/bash

IPADDRESS=$( hostname --ip-address)
export CLASSPATH=$CLASSPATH:..:.:/mnt/c/Users/daniele.ruffini/IdeaProjects/FDFS/out/production/FDFS

#java -Djava.security.policy=local.java.policy -classpath /mnt/c/Users/daniele.ruffini/IdeaProjects/FDFS/out/production/FDFS -Djava.rmi.server.hostname=$IPADDRESS com.rmi.FDFS.FileServerImpl $1

java  -Djava.security.policy=local.java.policy -Djava.rmi.server.hostname=$IPADDRESS com.rmi.FileServerImpl $1
