#! /bin/bash

#IPADDRESS=$( hostname --ip-address)
export CLASSPATH=$CLASSPATH:..:.:/mnt/c/Users/daniele.ruffini/IdeaProjects/FDFS/out/production/FDFS

#java -Djava.security.policy=local.java.policy -classpath /home/faffo/IdeaProjects/FDFS/out/production/FDFS -Djava.rmi.server.hostname=$IPADDRESS com.rmi.FDFS.FileServerImpl $1

java  -Djava.security.policy=local.java.policy com.rmi.Client
