#! /bin/bash

IPADDRESS=$( hostname --ip-address)
export CLASSPATH=$CLASSPATH:..:.:out/production/FDFS

java  -Djava.security.policy=local.java.policy -Djava.rmi.server.hostname=$IPADDRESS com.rmi.FileServerImpl $1
